name: serverless-jams

frontend:
  component: '@serverless/website'
  inputs:
    code:
      src: react/dist
      root: frontend
      # hook: npm run build # Use this to build the site before deployment
    env:
      apiUrl: apiurl.com/vote # Replace this with the URL from your API
    domain: www.serverlessjams.com # Insert your custom domain here after registering it on Route53