org: fernando
app: serverlessjams
service: serverless-jams

frameworkVersion: ">=1.53.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  region: us-east-1

functions:
  recordSongVote:
  getSongVoteCount:

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: voteCounts
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: www.serverlessjams.com
    distributionFolder: frontend